=== FredericHeem/starhackit/server/src/plugins/users/raml/user.out.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "username": {
      "type": "string",
      "format": "username"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "first_name": {
      "type": "string",
      "format": "first_name"
    },
    "last_name": {
      "type": "string"
    },
    "created_at": {
      "type": "string",
      "format": "datePast"
    },
    "updated_at": {
      "type": "string",
      "format": "datePast"
    },
    "profile": {
      "type": "object",
      "properties": {
        "biography": {
          "type": "string"
        }
      },
      "required": ["biography"]
    }
  },
  "required": [
    "id",
    "username",
    "email",
    "first_name",
    "last_name",
    "created_at",
    "updated_at",
    "profile"
  ]
}

=== FredericHeem/starhackit/server/src/plugins/users/raml/user.out.sample.json
{
  "id": "6fba6aca-db12-4eb1-8ae6-918cf20e0f8c",
  "username": "Laura.Jennie.Reeves",
  "email": "Laura.Jennie.Reeves@mail.com",
  "first_name": "Laura",
  "last_name": "Jennie",
  "created_at": "2016-05-28T15:00:56.358Z",
  "updated_at": "2016-05-28T15:00:56.358Z",
  "profile": {
    "biography": "Ciao"
  }
}
